export const JOURNAL_PROMPTS = [
  'What moment stays with you from today?',
  'Where did you resist today?',
  'What small thing went unnoticed?',
  'How does your body feel as you sit here now?',
  'Where did you surprise yourself?',
  'What did you avoid?',
  'Were you here today, or somewhere else?',
  'What would you do differently if today could begin again?',
  'What are you carrying that you could put down?',
  'Where did you tell the truth today?',
  'Where did you hold back?',
  'What are you grateful for, without performing?',
  'What did you learn about yourself today?',
  'Where did you feel most alive?',
  'Where did you feel most numb?',
  'What conversation mattered?',
  'What did you need that you did not ask for?',
  'How did you care for yourself today?',
  'How did you neglect yourself today?',
  'What is asking for your attention?',
  'What would stillness tell you right now?',
  'What are you not saying?',
  'Where did you choose ease today?',
  'Where did you choose difficulty?',
  'What would you tell your younger self about today?',
  'What are you ready to release?',
  'What are you ready to welcome?',
  'How did today change you?',
  'What did you see clearly for the first time?',
  'What question is living in you tonight?',
  'Where did you meet yourself with kindness?',
  'Where did you meet yourself with judgment?',
  'What would make tomorrow a little gentler?',
  'What is true that you have been afraid to admit?',
  'What do you need to hear tonight?',
  'How did you show up for someone else?',
  'How did you show up for yourself?',
  'What is unfinished?',
  'What is complete?',
  'What would love do with today?',
  'Where did you belong today?',
  'Where did you feel like an outsider?',
  'What are you becoming?',
  'What are you leaving behind?',
  'What word describes today?',
  'What did today ask of you?',
  'What did you give?',
  'What did you withhold?',
  'How will you meet tomorrow?',
  'What matters most right now?',
  'What can wait until tomorrow?',
  'What is the one thing you want to remember from today?',
  'Where did you find peace?',
  'Where did you lose it?',
  'What would your breath say if it could speak?',
  'What is the weight you are carrying?',
  'What would rest look like tonight?',
  'What do you need to forgive?',
  'What do you need to thank?',
  'What is the quiet truth under the noise of the day?',
  'How did you tend the flame today?',
  'What will you take into sleep with you?',
  'What will you leave behind when you close your eyes?',
  'Who were you today?',
  'Who do you want to be tomorrow?',
]
