export const DAILY_QUOTES = [
  'The obstacle is the way.',
  'What we do now echoes in eternity.',
  'You have power over your mind, not outside events.',
  'Be a lamp unto yourself.',
  'Do not seek to have events happen as you want them to, but instead want them to happen as they do happen.',
  'The mind is everything. What you think you become.',
  'Waste no more time arguing what a good man should be. Be one.',
  'It is not the mountain we conquer but ourselves.',
  'Peace comes from within. Do not seek it without.',
  'We suffer more often in imagination than in reality.',
  'The happiness of your life depends upon the quality of your thoughts.',
  'When you arise in the morning, think of what a precious privilege it is to be alive.',
  'Very little is needed to make a happy life.',
  'Look within. Within is the fountain of good.',
  'He who lives in harmony with himself lives in harmony with the universe.',
  'Nothing external to you has any power over you.',
  'Dwell on the beauty of life. Watch the stars, and see yourself running with them.',
  'Accept the things to which fate binds you.',
  'The soul becomes dyed with the color of its thoughts.',
  'Knowing yourself is the beginning of all wisdom.',
  'The only way out is through.',
  'What you do not wish for yourself, do not do to others.',
  'Let your plans be dark and impenetrable as night.',
  'In the midst of movement and chaos, keep stillness inside of you.',
  'The present moment is the only moment over which we have dominion.',
  'We are what we repeatedly do. Excellence, then, is not an act but a habit.',
  'It does not matter how slowly you go so long as you do not stop.',
  'The wise man does not grow old, but ripens.',
  'Be still and know.',
  'All we have is this moment. Nothing else exists.',
  'Where attention goes, energy flows.',
  'The quieter you become, the more you can hear.',
  'Let go or be dragged.',
  'Between stimulus and response there is a space. In that space is our power to choose.',
  'The unexamined life is not worth living.',
  'To know thyself is the beginning of wisdom.',
  'What is essential is invisible to the eye.',
]
